# Generated by Django 3.2.8 on 2021-10-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubic_departamento', models.CharField(max_length=50)),
                ('ubic_provincia', models.CharField(max_length=50)),
                ('ubic_distrito', models.CharField(max_length=50)),
                ('ubic_comunidad', models.CharField(max_length=50)),
                ('ubic_created', models.DateField(auto_now_add=True)),
                ('ubic_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio_codigo', models.CharField(max_length=50)),
                ('socio_categoria', models.CharField(max_length=50)),
                ('socio_tipo', models.CharField(max_length=50)),
                ('socio_parentesco', models.CharField(max_length=50)),
                ('socio_estado', models.CharField(max_length=50)),
                ('socio_created', models.DateField(auto_now_add=True)),
                ('socio_updated', models.DateField(auto_now=True)),
                ('parent_socio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio')),
                ('socio_persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('socio_ubic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.ubicacion')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
