# Generated by Django 3.2.8 on 2021-10-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn_nombre', models.CharField(max_length=50)),
                ('bvn_codigo', models.CharField(max_length=50)),
                ('bvn_fnacimiento', models.DateField()),
                ('bvn_genero', models.CharField(max_length=50)),
                ('bvn_estado', models.CharField(max_length=50)),
                ('bvn_created', models.DateField(auto_now_add=True)),
                ('bvn_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bovino',
                'verbose_name_plural': 'Bovinos',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza_nombre', models.CharField(max_length=50)),
                ('raza_estado', models.CharField(max_length=2)),
                ('raza_created', models.DateField(auto_now_add=True)),
                ('raza_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Control_produccion_leche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_fecha', models.DateField()),
                ('cpl_cantidad', models.CharField(max_length=50)),
                ('cpl_observacion', models.CharField(max_length=50)),
                ('cpl_created', models.DateField(auto_now_add=True)),
                ('cpl_updated', models.DateField(auto_now=True)),
                ('cpl_bovino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovino.bovino')),
            ],
            options={
                'verbose_name': 'Control_produccion_leche',
                'verbose_name_plural': 'Controles_produccion_leche',
            },
        ),
        migrations.AddField(
            model_name='bovino',
            name='bvn_raza_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovino.raza'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='bvn_socio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio'),
        ),
    ]
