# Generated by Django 3.2.8 on 2021-10-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tractor', '0001_initial'),
        ('operario', '0001_initial'),
        ('tracto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implemento_agricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_codigo', models.CharField(max_length=50)),
                ('ia_modelo', models.CharField(max_length=50)),
                ('ia_ancho', models.CharField(max_length=50)),
                ('ia_potencia', models.CharField(max_length=50)),
                ('ia_peso', models.CharField(max_length=50)),
                ('ia_created', models.DateField(auto_now_add=True)),
                ('ia_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha_control',
                'verbose_name_plural': 'Fichas_control',
            },
        ),
        migrations.CreateModel(
            name='Ficha_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_fecha_inicio', models.DateField()),
                ('fc_fecha_fin', models.DateField()),
                ('fc_ia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_control.implemento_agricola')),
                ('fc_operario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operario.operario')),
                ('fc_tractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor')),
            ],
            options={
                'verbose_name': 'Ficha_control',
                'verbose_name_plural': 'Fichas_control',
            },
        ),
        migrations.CreateModel(
            name='Detalle_ficha_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfc_observaciones', models.CharField(max_length=50)),
                ('dfc_importe', models.CharField(max_length=50)),
                ('dfc_created', models.DateField(auto_now_add=True)),
                ('dfc_updated', models.DateField(auto_now=True)),
                ('dfc_fc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_control.ficha_control')),
                ('dfc_tracto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracto.tracto')),
            ],
            options={
                'verbose_name': 'Detalle_ficha_control',
                'verbose_name_plural': 'Detalles_ficha_control',
            },
        ),
    ]
