# Generated by Django 3.2.8 on 2021-10-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_codigo', models.CharField(max_length=50)),
                ('oper_especialidad', models.CharField(max_length=50)),
                ('oper_created', models.DateField(auto_now_add=True)),
                ('oper_updated', models.DateField(auto_now=True)),
                ('oper_persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
            },
        ),
    ]
