# Generated by Django 3.2.8 on 2021-10-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_operante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ao_hectareas', models.CharField(max_length=50)),
                ('ao_created', models.DateField(auto_now_add=True)),
                ('ao_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area_operante',
                'verbose_name_plural': 'Areas_operantes',
            },
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_nombre', models.CharField(max_length=50)),
                ('sem_marca', models.CharField(max_length=50)),
                ('sem_calidad', models.CharField(max_length=50)),
                ('sem_procedencia', models.CharField(max_length=50)),
                ('sem_descripcion', models.CharField(max_length=50)),
                ('sem_created', models.DateField(auto_now_add=True)),
                ('sem_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semilla',
                'verbose_name_plural': 'Semillas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_forraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_nombre', models.CharField(max_length=50)),
                ('tf_created', models.DateField(auto_now_add=True)),
                ('tf_updated', models.DateField(auto_now=True)),
                ('tf_semilla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predio.semilla')),
            ],
            options={
                'verbose_name': 'Tipo_forraje',
                'verbose_name_plural': 'Tipos_forrajes',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_area_total', models.CharField(max_length=50)),
                ('pred_area_pasiva', models.CharField(max_length=50)),
                ('pred_created', models.DateField(auto_now_add=True)),
                ('pred_updated', models.DateField(auto_now=True)),
                ('pred_socio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='Detalle_area_operante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_inicio', models.DateField()),
                ('dao_fin', models.DateField()),
                ('dao_created', models.DateField(auto_now_add=True)),
                ('dao_updated', models.DateField(auto_now=True)),
                ('dao_ao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predio.area_operante')),
                ('dao_tf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predio.tipo_forraje')),
            ],
            options={
                'verbose_name': 'Detalle_area_operante',
                'verbose_name_plural': 'Detalles_areas_operantes',
            },
        ),
        migrations.AddField(
            model_name='area_operante',
            name='ao_predio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predio.predio'),
        ),
    ]
